Resolucion Batalla naval
MaxiBis/aydoo-2018 pull request #1
Opened 2018-04-11 05:13 UTC by MaxiBis

2018-04-18 02:30 UTC, anero requested changes

2018-04-18 02:30 UTC, anero commented on batallaNaval/src/main/java/ar/edu/untref/aydoo/Barco.java
> +        return posiciones;
Al devolver una referencia a la lista de posiciones interna estas rompiendo el encapsulamiento

2018-04-18 02:30 UTC, anero commented on batallaNaval/src/main/java/ar/edu/untref/aydoo/Barco.java
> +        List<Posicion> posiciones = this.getListaDePosiciones();
Si estás dentro de la clase podes acceder directamente al atributo `posiciones`, no es necesario invocar a `getListaDePosiciones`

2018-04-18 02:30 UTC, anero commented on batallaNaval/src/main/java/ar/edu/untref/aydoo/Barco.java
> +        Posicion posicionDelCrucero;
Estamos en la clase `Barco`, por qué te referís al crucero acá?

2018-04-18 02:30 UTC, anero commented on batallaNaval/src/main/java/ar/edu/untref/aydoo/Barco.java
> +        for (ListIterator<Posicion> iterador = posiciones.listIterator(); iterador.hasNext(); ) {
Fijate porque hay formas más fáciles de iterar sobre una colección en las versiones modernas de Java

2018-04-18 02:30 UTC, anero commented on batallaNaval/src/main/java/ar/edu/untref/aydoo/Barco.java
> +                salida = true;
Nombre de variable poco claro

2018-04-18 02:30 UTC, anero commented on batallaNaval/src/main/java/ar/edu/untref/aydoo/Bote.java
> +        this.posiciones = new ArrayList<Posicion>();
El atributo está declarado en la clase base, corresponde que sea ahí donde se inicializa

2018-04-18 02:30 UTC, anero commented on batallaNaval/src/main/java/ar/edu/untref/aydoo/Bote.java
> +    public Posicion getPosicion() {
Este método parece innecesario, lo mismo lo podrías hacer con `getListaDePosiciones` (la colección en ese caso tendría siempre un único elemento)

2018-04-18 02:30 UTC, anero commented on batallaNaval/src/main/java/ar/edu/untref/aydoo/Bote.java
> +    public void agregarPosicion(Posicion posicion) {
Si el método tiene la misma implementación para todas las sub-clases de `Barco` deberías definirlo en la clase base

2018-04-18 02:30 UTC, anero commented on batallaNaval/src/main/java/ar/edu/untref/aydoo/Bote.java
> +    public void agregarPosicion(Posicion posicion) {
Por otro lado en ningún momento validas que la cantidad de posiciones del barco coincida sea menor o igual a la longitud total (1 para el bote, 2 para el crucero). 
Tampoco se valida que las posiciones sean consecutivas.

2018-04-18 02:30 UTC, anero commented on batallaNaval/src/main/java/ar/edu/untref/aydoo/Posicion.java
> +    private Disparo estado;
Los atributos tienen varias inconsistencias:
- La posición tiene un disparo?
- `esAgua` debería ser calculable (si no hay un barco o `estado` es `Disparo.AGUA` entonces _es agua_)
- El nombre `elBarcoQueTieneLaPosicion` me parece un tanto repetitivo. Si estamos hablando de un atributo de la posición es claro que _lo tiene_ la posición

2018-04-18 02:30 UTC, anero commented on batallaNaval/src/main/java/ar/edu/untref/aydoo/Disparo.java
> +public enum Disparo {
El nombre del enumerado me hace ruido. El disparo puede ser _tocado_ o _hundido_?

2018-04-18 02:30 UTC, anero commented on batallaNaval/src/main/java/ar/edu/untref/aydoo/Posicion.java
> +    public boolean esIgualA(Posicion posicionAComparar) {
A modo informativo podrías sobreescribir el método `equals` que tienen todos los objetos en Java para implementar esta comparación de forma estandar

2018-04-18 02:30 UTC, anero commented on batallaNaval/src/main/java/ar/edu/untref/aydoo/Posicion.java
> +            return false;
Todo esto también se puede escribir más sucintamente como:
`return this.getPosicionVertical() == posicionAComparar.getPosicionVertical() && this.getPosicionHorizontal() == posicionAComparar.getPosicionHorizontal()`

2018-04-18 02:30 UTC, anero commented on batallaNaval/src/main/java/ar/edu/untref/aydoo/Posicion.java
> +}
Esta clase no tiene ningún comportamiento, son todos setters y getters

2018-04-18 02:30 UTC, anero commented on batallaNaval/src/main/java/ar/edu/untref/aydoo/Tablero.java
> +        if (this.estaDentroDeLimites(posicion, 1)) {
Este método debería ser el mismo para `Bote` y `Crucero`, en vez de hardcodear el tamaño podrías preguntarle al objeto `Barco` que recibas por parámetro y chequear que pueda ocupar todas las posiciones deseadas

2018-04-18 02:30 UTC, anero commented on batallaNaval/src/main/java/ar/edu/untref/aydoo/Tablero.java
> +        if (this.estaDentroDeLimites(posicion, 1)) {
Lo mismo para la orientación, tanta repetición de código debería hacerte ruido...

2018-04-18 02:30 UTC, anero commented on batallaNaval/src/main/java/ar/edu/untref/aydoo/Tablero.java
> +        if ((posicionAProbar.getPosicionHorizontal() - 1 + tamano) < posiciones.length && (posicionAProbar.getPosicionVertical() - 1 + tamano) < posiciones.length)
No entiendo que es lo que estás verificando acá, no necesitas saber cuál es la orientación del barco para saber si está o no dentro de los límites?

2018-04-18 02:30 UTC, anero commented on batallaNaval/src/test/java/ar/edu/untref/aydoo/IntegracionTest.java
> +}
- Faltan tests de otras clases.
- Faltan pruebas sobre casos límite y excepcionales

2018-04-30 01:12 UTC, merged

2018-05-07 00:33 UTC, MaxiBis commented on batallaNaval/src/main/java/ar/edu/untref/aydoo/Bote.java
> +    public Posicion getPosicion() {
este lo tenia xq era un caso de cuando empezaba con un barco solo, lo modifique

2018-05-07 00:34 UTC, MaxiBis commented on batallaNaval/src/main/java/ar/edu/untref/aydoo/Bote.java
> +    public void agregarPosicion(Posicion posicion) {
ahi le puse algo de logica, que me habia quedado pendiente de hacer. La validacion de posiciones consecutivas las hace el tablero, me parecia mejor xq el tablero conoce los limites del mismo, y ademas que barcos estan ahi

2018-05-07 00:34 UTC, MaxiBis commented on batallaNaval/src/main/java/ar/edu/untref/aydoo/Posicion.java
> +    private Disparo estado;
Si, la posición tiene un Disparo, ponerle disparo no es el mejor nombre, ponerle algo tipo estadoDeUnaPosicion al enum seria mejor? mas legible asi? 
esAgua quedo del diseño inicial, lo saque, lo mismo con elBarcoQueTieneLaPosicion

2018-05-07 01:18 UTC, anero commented on batallaNaval/src/main/java/ar/edu/untref/aydoo/Posicion.java
> +    private Disparo estado;
Creo que al revés `disparo` sería mejor nombre para el atributo que `estado`, dado que el atributo puede ser `null` y es raro que un objeto no tenga estado