Libreria
MaxiBis/aydoo-2018 pull request #3
Opened 2018-04-24 04:09 UTC by MaxiBis

2018-04-29 10:12 UTC, anero requested changes

2018-04-29 10:12 UTC, anero commented on libreria/src/it/java/ar/edu/untref/aydoo/AcceptanceTest.java
> +}
Código innecesario

2018-04-29 10:12 UTC, anero commented on libreria/src/main/java/ar/edu/untref/aydoo/ArticuloDeLibreria.java
> +        return (int)(this.precio*1.21);
Si tenés que castear el resultado capaz que usar un `int` para el precio no es lo más apropiado... Con esto estas perdiendo información (básicamente estás redondeando y perdiendo centavos en cada calculo).

2018-04-29 10:12 UTC, anero commented on libreria/src/main/java/ar/edu/untref/aydoo/Cliente.java
> +        System.out.println("saleCada: " + saleCada);
código de debugging

2018-04-29 10:12 UTC, anero commented on libreria/src/main/java/ar/edu/untref/aydoo/Cliente.java
> +        Compra compraNueva = new Compra (productoComprado,19,12,1990);
Esto no cumple la consigna del ejercicio, las compras se realizan en una fecha puntual. Si le asignas cualquier fecha es imposible calcular las compras para un período determinado. Y setearle la fecha a la compra después de realizarla como haces en los tests tampoco es correcto.
Tal vez el método `comprar` debería _saber_ en que fecha se hizo la compra?

2018-04-29 10:12 UTC, anero commented on libreria/src/main/java/ar/edu/untref/aydoo/Cliente.java
> +                return (int)(total * 0.95);
No se cumple la consigna: los descuentos no son acumulables.

2018-04-29 10:12 UTC, anero commented on libreria/src/main/java/ar/edu/untref/aydoo/Cliente.java
> +            this.comprar(publicacionACargar);
Del enunciado no es claro si las suscripciones se cobran por adelantado o mes a mes. Vos acá estás asumiendo que se cobran por adelantado (lo que es correcto), pero sería bueno que lo incluyas como hipótesis en el `README`

2018-04-29 10:12 UTC, anero commented on libreria/src/main/java/ar/edu/untref/aydoo/Cliente.java
> +    public Compra getCompra() {
Este método es confuso, ¿porque necesitas una forma de obtener solo la primer compra? Si realmente es necesario el método debería llamarse de una forma que haga explícito que se trata de la primer compra de varias posibles.

2018-04-29 10:12 UTC, anero commented on libreria/src/main/java/ar/edu/untref/aydoo/Compra.java
> +    //private Producto productoDeLaCompra;
código comentado

2018-04-29 10:12 UTC, anero commented on libreria/src/main/java/ar/edu/untref/aydoo/Compra.java
> +        System.out.println(this.getDia());*/
más código comentado

2018-04-29 10:12 UTC, anero commented on libreria/src/main/java/ar/edu/untref/aydoo/Compra.java
> +        fecha = sdf.getCalendar();
se debería usar la fecha recibida por parámetro, no la fecha actual

2018-04-29 10:12 UTC, anero commented on libreria/src/main/java/ar/edu/untref/aydoo/Libro.java
> +        super(i);
¿qué es el parámetro `i`? Nombres claros para las variables por favor!

2018-05-08 00:17 UTC, MaxiBis commented on libreria/src/main/java/ar/edu/untref/aydoo/Cliente.java
> +        Compra compraNueva = new Compra (productoComprado,19,12,1990);
en realidad, le paso una fecha pero adentro del constructor seteaba la fecha actual.
Mi idea(y como lo hice ahora), era hacer otro constructor sin fecha, se me paso.

2018-05-08 00:17 UTC, MaxiBis commented on libreria/src/main/java/ar/edu/untref/aydoo/Cliente.java
> +            this.comprar(publicacionACargar);
estaba aclarado

2018-05-08 00:18 UTC, MaxiBis commented on libreria/src/main/java/ar/edu/untref/aydoo/Cliente.java
> +    public Compra getCompra() {
Me paso lo mismo en la batalla naval, por la manera incremental de ir haciendo crecer los tests, primero el cliente tenia una sola compra y despues puse una lista. 
lo cambie.

2018-05-08 00:18 UTC, MaxiBis commented on libreria/src/main/java/ar/edu/untref/aydoo/Compra.java
> +        fecha = sdf.getCalendar();
si, me confundi y no hice el otro constructor

2018-05-08 03:03 UTC, closed without merging